# Travis-CI build file for GLPong
# See http://travis-ci.org for details

language: cpp

compiler:
  - gcc
  - clang

sudo: required

before_install:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz &&
   tar xf cmake-3.2.2.tar.gz &&
    cd cmake-3.2.2 &&
     ./configure &&
      make &&
       sudo make install &&
       cd ..
  - sudo apt-get update

install:
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev

# Run the build script
script:
  - mkdir build
  - cd build
  - cmake ..